version: "3.8"

services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dolcera_db
    ports:
      - "5432:5432"
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    
  backend:
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: dolcera-api
    command: /app/startup.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:8000"
    depends_on:
      - postgres_db
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:5050"
    depends_on:
      - postgres_db

volumes:
  data: