version: '3.8'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dolcera_db
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    command: /app/startup.sh
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - '${PORT}:8000'
    depends_on:
      - postgres_db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./frontend:/app

volumes:
  data:
