"""Add account_access_points table

Revision ID: 75de5ba2ea26
Revises: 596af22f87fb
Create Date: 2023-04-12 08:16:10.042293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75de5ba2ea26'
down_revision = '596af22f87fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_access_points',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('ap_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('serial_id', sa.String(length=255), nullable=True),
        sa.Column('qr_code', sa.String(length=255), nullable=True),
        sa.Column('nr_band', sa.String(length=255), nullable=True),
        sa.Column('nr_bandwidth', sa.String(length=255), nullable=True),
        sa.Column('tx_gain', sa.String(length=255), nullable=True),
        sa.Column('rx_gain', sa.String(length=255), nullable=True),
        sa.Column('epc_plmn', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['ap_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_access_points_id'), 'account_access_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_access_points_id'), table_name='account_access_points')
    op.drop_table('account_access_points')
    # ### end Alembic commands ###
