"""added status field in account_access_points table.

Revision ID: e166e3d60826
Revises: 2b27db73086a
Create Date: 2023-04-18 14:04:06.447436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e166e3d60826'
down_revision = '2b27db73086a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_access_points', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_access_points', 'status')
    # ### end Alembic commands ###
