export const FETCH_FACILITY_START = "FETCH_FACILITY_START";
export const FETCH_FACILITY_SUCCESS = "FETCH_FACILITY_SUCCESS";
export const FETCH_FACILITY_FAILURE = "FETCH_FACILITY_FAILURE";

export const FETCH_APPLICATIONS_START = "FETCH_APPLICATIONS_START";
export const FETCH_APPLICATIONS_SUCCESS = "FETCH_APPLICATIONS_SUCCESS";
export const FETCH_APPLICATIONS_FAILURE = "FETCH_APPLICATIONS_FAILURE";

export const CREATE_ACCOUNT_FACILITIES_START =
  "CREATE_ACCOUNT_FACILITIES_START";
export const CREATE_ACCOUNT_FACILITIES_SUCCESS =
  "CREATE_ACCOUNT_FACILITIES_SUCCESS";
export const CREATE_ACCOUNT_FACILITIES_FAILURE =
  "CREATE_ACCOUNT_FACILITIES_FAILURE";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ACCOUNT_ACCESS_POINT_START =
  "CREATE_ACCOUNT_ACCESS_POINT_START";
export const CREATE_ACCOUNT_ACCESS_POINT_SUCCESS =
  "CREATE_ACCOUNT_ACCESS_POINT_SUCCESS";
export const CREATE_ACCOUNT_ACCESS_POINT_FAILURE =
  "CREATE_ACCOUNT_ACCESS_POINT_FAILURE";
