"""Added facility table

Revision ID: 18337d71c2eb
Revises: 78bbccf7d61e
Create Date: 2023-04-10 11:57:58.881347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18337d71c2eb'
down_revision = '78bbccf7d61e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=True),
    sa.Column('is_other', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
