"""Update add_type_to_product_table

Revision ID: 24bdb53d83ac
Revises: 75de5ba2ea26
Create Date: 2023-04-12 09:49:04.135206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bdb53d83ac'
down_revision = '75de5ba2ea26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type')
    # ### end Alembic commands ###
