"""Add field to Products

Revision ID: 596af22f87fb
Revises: f1e60fe7c54b
Create Date: 2023-04-12 08:14:13.798060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596af22f87fb'
down_revision = 'f1e60fe7c54b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('desciprition', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_preview', sa.Boolean(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('products', 'is_preview')
    op.drop_column('products', 'link')
    op.drop_column('products', 'desciprition')
    # ### end Alembic commands ###
